export type TrainerMove = {
  side: "white" | "black";
  san: string;
  uci: string;
  idea: string;
};

export type OpeningLine = {
  id: string;
  title: string;
  family: string;
  difficulty: "Core" | "Sharp" | "Strategic";
  goal: string;
  moves: TrainerMove[];
};

export type OpeningCourse = {
  id: "sicilian" | "kings-indian";
  name: string;
  shortName: string;
  userSide: "black";
  summary: string;
  plans: string[];
  lines: OpeningLine[];
};

const black = (san: string, uci: string, idea: string): TrainerMove => ({
  side: "black",
  san,
  uci,
  idea,
});

const white = (san: string, uci: string, idea = "Opponent move."): TrainerMove => ({
  side: "white",
  san,
  uci,
  idea,
});

export const openingCourses: OpeningCourse[] = [
  {
    id: "sicilian",
    name: "Sicilian Defense",
    shortName: "Sicilian",
    userSide: "black",
    summary:
      "A fighting response to 1.e4. Black accepts an asymmetrical pawn structure, trades the c-pawn for White's d-pawn, and plays for queenside counterplay while White often attacks the king.",
    plans: [
      "Fight for d4 with ...cxd4 and develop the kingside quickly.",
      "Use ...d6 or ...e6 to control central breaks before choosing your setup.",
      "Watch White's attacking plan; many Sicilian lines are a race between wings.",
      "Your recurring themes are ...a6, ...b5, ...Qc7, ...Rc8, and timely central breaks.",
    ],
    lines: [
      {
        id: "najdorf-english",
        title: "Najdorf: English Attack",
        family: "Najdorf",
        difficulty: "Sharp",
        goal: "Learn the classic ...a6, ...e5, ...Be6 setup against White's queenside castling plan.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Challenge the center from the side and create an unbalanced game immediately."),
          white("Nf3", "g1f3"),
          black("d6", "d7d6", "Support ...Nf6 without allowing e5 to kick the knight for free."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Trade your c-pawn for White's central d-pawn, the core Sicilian bargain."),
          white("Nxd4", "f3d4"),
          black("Nf6", "g8f6", "Develop with tempo on e4 and force White to defend the center."),
          white("Nc3", "b1c3"),
          black("a6", "a7a6", "The Najdorf move. It controls b5 and prepares queenside expansion."),
          white("Be3", "c1e3"),
          black("e5", "e7e5", "Hit the knight and claim dark-square space, accepting a backward d6 pawn."),
          white("Nb3", "d4b3"),
          black("Be6", "c8e6", "Develop toward the queenside and challenge White's attacking bishop."),
          white("f3", "f2f3"),
          black("Be7", "f8e7", "Prepare castling and keep the king compact before White launches pawns."),
          white("Qd2", "d1d2"),
          black("O-O", "e8g8", "Get the king safe before opening queenside counterplay."),
          white("O-O-O", "e1c1"),
          black("Nbd7", "b8d7", "Bring the last minor piece in and prepare ...b5 or ...Rc8."),
        ],
      },
      {
        id: "dragon-yugoslav",
        title: "Dragon: Yugoslav Attack",
        family: "Dragon",
        difficulty: "Sharp",
        goal: "Practice the Dragon setup where Black fianchettoes and aims the bishop down the long diagonal.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Start the Sicilian imbalance and avoid symmetrical e-pawn structures."),
          white("Nf3", "g1f3"),
          black("d6", "d7d6", "Keep e5 under control and prepare a flexible Dragon structure."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Remove White's central pawn before it gains space."),
          white("Nxd4", "f3d4"),
          black("Nf6", "g8f6", "Attack e4 and develop naturally."),
          white("Nc3", "b1c3"),
          black("g6", "g7g6", "Signal the Dragon and prepare a powerful bishop on g7."),
          white("Be3", "c1e3"),
          black("Bg7", "f8g7", "Put the bishop on the long diagonal toward c3 and b2."),
          white("f3", "f2f3"),
          black("Nc6", "b8c6", "Add pressure to d4 and complete queenside development."),
          white("Qd2", "d1d2"),
          black("O-O", "e8g8", "Castle before White's h-pawn and queenside castling attack arrives."),
          white("Bc4", "f1c4"),
          black("Bd7", "c8d7", "Clear c8 for the rook and prepare direct pressure on the c-file."),
          white("O-O-O", "e1c1"),
          black("Rc8", "a8c8", "Put the rook on the same file as White's king."),
        ],
      },
      {
        id: "sveshnikov",
        title: "Sveshnikov",
        family: "Sveshnikov",
        difficulty: "Sharp",
        goal: "Learn the active ...e5 system where Black accepts d5 weakness for piece activity.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Create the Sicilian structure and fight for d4."),
          white("Nf3", "g1f3"),
          black("Nc6", "b8c6", "Develop while increasing control of d4 and e5."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Trade into the open Sicilian structure."),
          white("Nxd4", "f3d4"),
          black("Nf6", "g8f6", "Attack e4 and invite Nc3."),
          white("Nc3", "b1c3"),
          black("e5", "e7e5", "The Sveshnikov strike: gain space and force the knight to b5."),
          white("Ndb5", "d4b5"),
          black("d6", "d7d6", "Defend e5 and keep White's knight contained."),
          white("Bg5", "c1g5"),
          black("a6", "a7a6", "Ask the knight where it is going and prepare ...b5."),
          white("Na3", "b5a3"),
          black("b5", "b7b5", "Gain queenside space and challenge the knight on a3."),
          white("Nd5", "c3d5"),
          black("Be7", "f8e7", "Develop and prepare to question the bishop."),
          white("Bxf6", "g5f6"),
          black("Bxf6", "e7f6", "Recapture with the bishop and keep central dark-square control."),
        ],
      },
      {
        id: "classical-rauzer",
        title: "Classical: Richter-Rauzer",
        family: "Classical",
        difficulty: "Core",
        goal: "Use fast development and a central queen move to meet White's queenside castling setup.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Begin with the standard Sicilian challenge."),
          white("Nf3", "g1f3"),
          black("d6", "d7d6", "Support ...Nf6 and keep e5 controlled."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Remove White's central pawn."),
          white("Nxd4", "f3d4"),
          black("Nf6", "g8f6", "Develop and attack e4."),
          white("Nc3", "b1c3"),
          black("Nc6", "b8c6", "Classical development with pressure on d4."),
          white("Bg5", "c1g5"),
          black("e6", "e7e6", "Blunt the bishop and prepare Be7."),
          white("Qd2", "d1d2"),
          black("Be7", "f8e7", "Develop safely and prepare castling."),
          white("O-O-O", "e1c1"),
          black("O-O", "e8g8", "Finish king safety before White attacks."),
          white("f4", "f2f4"),
          black("Nxd4", "c6d4", "Exchange a defender and reduce White's attacking force."),
          white("Qxd4", "d2d4"),
          black("Qa5", "d8a5", "Create pressure on c3 and keep an eye on the king."),
        ],
      },
      {
        id: "accelerated-dragon",
        title: "Accelerated Dragon: Maroczy Bind",
        family: "Accelerated Dragon",
        difficulty: "Strategic",
        goal: "Learn how Black develops smoothly against White's space-grabbing c4 setup.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Choose the Sicilian and avoid a classical pawn center."),
          white("Nf3", "g1f3"),
          black("Nc6", "b8c6", "Develop before committing the d-pawn."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Trade into the open Sicilian."),
          white("Nxd4", "f3d4"),
          black("g6", "g7g6", "Accelerate the Dragon bishop before playing ...d6."),
          white("c4", "c2c4"),
          black("Nf6", "g8f6", "Attack e4 and keep pressure on the center."),
          white("Nc3", "b1c3"),
          black("d6", "d7d6", "Stabilize the center and prepare development."),
          white("Be2", "f1e2"),
          black("Nxd4", "c6d4", "Trade before White fully clamps the bind."),
          white("Qxd4", "d1d4"),
          black("Bg7", "f8g7", "Develop the bishop with tempo ideas on d4."),
          white("Be3", "c1e3"),
          black("O-O", "e8g8", "Castle and prepare pressure on the queenside."),
          white("Qd2", "d4d2"),
          black("Be6", "c8e6", "Develop and target c4/d5 squares."),
        ],
      },
      {
        id: "taimanov",
        title: "Taimanov",
        family: "Taimanov",
        difficulty: "Core",
        goal: "Practice the flexible ...e6 and ...Qc7 setup before choosing your pawn breaks.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Create the Sicilian imbalance."),
          white("Nf3", "g1f3"),
          black("e6", "e7e6", "Prepare a flexible dark-square structure."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Exchange your c-pawn for White's d-pawn."),
          white("Nxd4", "f3d4"),
          black("Nc6", "b8c6", "Pressure d4 before committing the kingside knight."),
          white("Nc3", "b1c3"),
          black("Qc7", "d8c7", "Support e5 ideas and watch c3/e5."),
          white("Be3", "c1e3"),
          black("a6", "a7a6", "Stop Nb5 and prepare queenside space."),
          white("Qd2", "d1d2"),
          black("Nf6", "g8f6", "Develop and increase pressure on e4."),
          white("O-O-O", "e1c1"),
          black("Bb4", "f8b4", "Pin and provoke weaknesses near White's king."),
          white("f3", "f2f3"),
          black("Ne5", "c6e5", "Centralize and attack c4/d3/f3 squares."),
          white("Nb3", "d4b3"),
          black("b5", "b7b5", "Start queenside counterplay against the castled king."),
        ],
      },
      {
        id: "kan",
        title: "Kan",
        family: "Kan",
        difficulty: "Strategic",
        goal: "Use ...a6 and ...Qc7 to keep the structure flexible and delay the kingside knight.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Enter Sicilian territory."),
          white("Nf3", "g1f3"),
          black("e6", "e7e6", "Build a compact dark-square system."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Remove the central pawn."),
          white("Nxd4", "f3d4"),
          black("a6", "a7a6", "The Kan signature: stop Nb5 and stay flexible."),
          white("Bd3", "f1d3"),
          black("Nf6", "g8f6", "Develop and challenge e4."),
          white("O-O", "e1g1"),
          black("Qc7", "d8c7", "Connect pressure to c2 and e5."),
          white("Qe2", "d1e2"),
          black("d6", "d7d6", "Support e5 and prepare development."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Fianchetto to pressure the center from distance."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Complete the dark-square plan."),
          white("Be3", "c1e3"),
          black("O-O", "e8g8", "Castle into a stable structure."),
        ],
      },
      {
        id: "scheveningen",
        title: "Scheveningen",
        family: "Scheveningen",
        difficulty: "Strategic",
        goal: "Learn the compact ...e6/...d6 shell and prepare breaks without overextending.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Start with the Sicilian imbalance."),
          white("Nf3", "g1f3"),
          black("e6", "e7e6", "Prepare the Scheveningen center."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Trade into the open Sicilian."),
          white("Nxd4", "f3d4"),
          black("Nf6", "g8f6", "Develop and attack e4."),
          white("Nc3", "b1c3"),
          black("d6", "d7d6", "Complete the small-center shell."),
          white("Be2", "f1e2"),
          black("Be7", "f8e7", "Develop calmly and prepare castling."),
          white("O-O", "e1g1"),
          black("O-O", "e8g8", "Finish development before choosing a break."),
          white("f4", "f2f4"),
          black("a6", "a7a6", "Control b5 and prepare ...b5."),
          white("Be3", "c1e3"),
          black("Qc7", "d8c7", "Connect queen and rook ideas on the c-file."),
          white("a4", "a2a4"),
          black("b6", "b7b6", "Prepare Bb7 and contest central dark squares."),
        ],
      },
      {
        id: "alapin",
        title: "Alapin",
        family: "Anti-Sicilian",
        difficulty: "Core",
        goal: "Meet 2.c3 with active knight pressure and immediate central counterplay.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Keep the Sicilian identity."),
          white("c3", "c2c3"),
          black("Nf6", "g8f6", "Attack e4 before White builds d4 freely."),
          white("e5", "e4e5"),
          black("Nd5", "f6d5", "Occupy d5 and slow White's center."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Open the c-file and challenge the center."),
          white("Nf3", "g1f3"),
          black("Nc6", "b8c6", "Add pressure to d4 and e5."),
          white("Bc4", "f1c4"),
          black("Nb6", "d5b6", "Hit the bishop and clear d5 for tactics."),
          white("Bb3", "c4b3"),
          black("d5", "d7d5", "Strike the center before White consolidates."),
          white("exd6", "e5d6"),
          black("Qxd6", "d8d6", "Recapture with the queen and keep development flowing."),
          white("O-O", "e1g1"),
          black("Be6", "c8e6", "Develop and challenge the b3 bishop."),
          white("Re1", "f1e1"),
          black("Bxb3", "e6b3", "Remove an active bishop and simplify White's pressure."),
        ],
      },
      {
        id: "rossolimo",
        title: "Rossolimo",
        family: "Anti-Sicilian",
        difficulty: "Strategic",
        goal: "Handle Bb5 systems with a Dragon-like fianchetto and solid central play.",
        moves: [
          white("e4", "e2e4"),
          black("c5", "c7c5", "Keep the Sicilian imbalance."),
          white("Nf3", "g1f3"),
          black("Nc6", "b8c6", "Develop and invite Rossolimo pressure."),
          white("Bb5", "f1b5"),
          black("g6", "g7g6", "Fianchetto and avoid passive defense."),
          white("O-O", "e1g1"),
          black("Bg7", "f8g7", "Put the bishop on the long diagonal."),
          white("Re1", "f1e1"),
          black("e5", "e7e5", "Claim central dark squares and blunt the bishop."),
          white("c3", "c2c3"),
          black("Nge7", "g8e7", "Develop without blocking the fianchetto bishop."),
          white("d4", "d2d4"),
          black("cxd4", "c5d4", "Trade before White gets the full center."),
          white("cxd4", "c3d4"),
          black("exd4", "e5d4", "Open the e-file and remove White's pawn duo."),
          white("Bg5", "c1g5"),
          black("O-O", "e8g8", "Castle and complete king safety."),
          white("Bxc6", "b5c6"),
          black("dxc6", "d7c6", "Accept doubled pawns for bishop pair and central control."),
        ],
      },
    ],
  },
  {
    id: "kings-indian",
    name: "King's Indian Defense",
    shortName: "King's Indian",
    userSide: "black",
    summary:
      "A dynamic defense to 1.d4 where Black lets White build the center, then attacks it with ...e5 or ...c5 and often launches a kingside pawn storm.",
    plans: [
      "Fianchetto the dark-square bishop and castle quickly.",
      "Let White take space, then strike with ...e5 or ...c5.",
      "In closed centers, aim for ...f5 and kingside play.",
      "In fianchetto systems, use queenside pressure with ...Nc6, ...a6, ...Rb8, and ...b5.",
    ],
    lines: [
      {
        id: "kid-classical",
        title: "Classical Main Line",
        family: "Classical",
        difficulty: "Core",
        goal: "Build the standard King's Indian shell and learn the ...e5, ...Ne7, ...f5 plan.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Prevent e4 from becoming too easy and develop naturally."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the fianchetto, the soul of the King's Indian."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Put the bishop on the long diagonal toward d4."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Support e5 and keep the center under watch."),
          white("Nf3", "g1f3"),
          black("O-O", "e8g8", "Castle before opening the center."),
          white("Be2", "f1e2"),
          black("e5", "e7e5", "Challenge White's center at its base."),
          white("O-O", "e1g1"),
          black("Nc6", "b8c6", "Increase pressure and prepare central tension."),
          white("d5", "d4d5"),
          black("Ne7", "c6e7", "Reroute for ...Nd7 and ...f5."),
          white("Ne1", "f3e1"),
          black("Nd7", "f6d7", "Clear the f-pawn and support kingside expansion."),
          white("Be3", "c1e3"),
          black("f5", "f7f5", "Begin the thematic kingside attack."),
        ],
      },
      {
        id: "kid-samisch",
        title: "Samisch",
        family: "Samisch",
        difficulty: "Sharp",
        goal: "Meet White's f3 and long-castle setup with central tension and kingside counterplay.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Develop and challenge central expansion."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the dark-square bishop."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Aim at d4 and b2."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Hold the center and prepare ...e5."),
          white("f3", "f2f3"),
          black("O-O", "e8g8", "Castle before White can open files."),
          white("Be3", "c1e3"),
          black("e5", "e7e5", "Question the center before White castles long."),
          white("d5", "d4d5"),
          black("Nh5", "f6h5", "Head toward f4 and provoke kingside weaknesses."),
          white("Qd2", "d1d2"),
          black("f5", "f7f5", "Strike where White's king may soon live."),
          white("O-O-O", "e1c1"),
          black("Nd7", "b8d7", "Bring another piece toward f6/c5/e5."),
          white("Bd3", "f1d3"),
          black("Nf4", "h5f4", "Jump into an active outpost and pressure d3/e2."),
        ],
      },
      {
        id: "kid-four-pawns",
        title: "Four Pawns Attack",
        family: "Four Pawns",
        difficulty: "Sharp",
        goal: "Survive White's big center by breaking it down with ...c5 and ...e6.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Start by restraining e4."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the fianchetto."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Pressure the center from the long diagonal."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Support central counterplay."),
          white("f4", "f2f4"),
          black("O-O", "e8g8", "Get safe before the center opens."),
          white("Nf3", "g1f3"),
          black("c5", "c7c5", "Attack the overextended pawn chain from the side."),
          white("d5", "d4d5"),
          black("e6", "e7e6", "Undermine the pawn wedge immediately."),
          white("Be2", "f1e2"),
          black("exd5", "e6d5", "Open lines before White consolidates."),
          white("cxd5", "c4d5"),
          black("Re8", "f8e8", "Put a rook on the e-file and pressure e4."),
          white("e5", "e4e5"),
          black("dxe5", "d6e5", "Break the center and create tactical targets."),
        ],
      },
      {
        id: "kid-fianchetto",
        title: "Fianchetto Variation",
        family: "Fianchetto",
        difficulty: "Strategic",
        goal: "Play patiently against White's solid bishop on g2 and strike with ...e5 and ...c6.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Develop and control e4."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare your own fianchetto."),
          white("g3", "g2g3"),
          black("Bg7", "f8g7", "Match White's long diagonal with your bishop."),
          white("Bg2", "f1g2"),
          black("O-O", "e8g8", "Castle into the standard shell."),
          white("Nc3", "b1c3"),
          black("d6", "d7d6", "Prepare central play."),
          white("Nf3", "g1f3"),
          black("Nbd7", "b8d7", "Keep c6 available for pawns and support e5."),
          white("O-O", "e1g1"),
          black("e5", "e7e5", "Challenge the center at the right moment."),
          white("e4", "e2e4"),
          black("c6", "c7c6", "Prepare queenside expansion and support d5 ideas."),
          white("h3", "h2h3"),
          black("Re8", "f8e8", "Support e5 and prepare central tension."),
          white("Be3", "c1e3"),
          black("exd4", "e5d4", "Open the center once your pieces are coordinated."),
        ],
      },
      {
        id: "kid-averbakh",
        title: "Averbakh",
        family: "Averbakh",
        difficulty: "Strategic",
        goal: "React to Bg5 by using ...c5 and ...e6 to challenge White's center before the pin matters.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Develop with central control."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the fianchetto."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Complete the diagonal setup."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Support ...e5 and control central squares."),
          white("Be2", "f1e2"),
          black("O-O", "e8g8", "Castle before opening play."),
          white("Bg5", "c1g5"),
          black("c5", "c7c5", "Counterattack the center instead of passively answering the pin."),
          white("d5", "d4d5"),
          black("e6", "e7e6", "Undermine the advanced pawn chain."),
          white("Qd2", "d1d2"),
          black("exd5", "e6d5", "Open lines and challenge White's space."),
          white("cxd5", "c4d5"),
          black("Re8", "f8e8", "Put pressure on e4 and coordinate rooks."),
          white("f3", "f2f3"),
          black("a6", "a7a6", "Prepare queenside counterplay with ...b5."),
        ],
      },
      {
        id: "kid-petrosian",
        title: "Petrosian System",
        family: "Classical",
        difficulty: "Strategic",
        goal: "Handle d5 without rushing; use ...a5 and ...Na6 to slow White's queenside play.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Begin with flexible development."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the bishop on g7."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Fight along the long diagonal."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Support central breaks."),
          white("Nf3", "g1f3"),
          black("O-O", "e8g8", "Castle into safety."),
          white("Be2", "f1e2"),
          black("e5", "e7e5", "Strike the center."),
          white("d5", "d4d5"),
          black("a5", "a7a5", "Stop b4 expansion and gain queenside space."),
          white("Bg5", "c1g5"),
          black("h6", "h7h6", "Ask the bishop to choose and gain luft."),
          white("Bh4", "g5h4"),
          black("Na6", "b8a6", "Route the knight toward c5 or b4."),
          white("Nd2", "f3d2"),
          black("Qe8", "d8e8", "Prepare kingside coordination and possible ...Nh5."),
        ],
      },
      {
        id: "kid-makogonov",
        title: "Makogonov",
        family: "h3 Systems",
        difficulty: "Strategic",
        goal: "Respond to h3 with fast central play and a knight jump to h5/f4.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Control e4 and develop."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the fianchetto."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Aim at the center."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Keep the center ready for ...e5."),
          white("h3", "h2h3"),
          black("O-O", "e8g8", "Castle and do not overreact to h3."),
          white("Be3", "c1e3"),
          black("e5", "e7e5", "Challenge the pawn center immediately."),
          white("d5", "d4d5"),
          black("Nh5", "f6h5", "Head toward f4 and put pressure on dark squares."),
          white("g3", "g2g3"),
          black("f5", "f7f5", "Launch the standard kingside break."),
          white("exf5", "e4f5"),
          black("Bxf5", "c8f5", "Develop with capture and keep active pieces."),
          white("Bg2", "f1g2"),
          black("Nf6", "h5f6", "Return the knight to support e4 and g4 ideas."),
        ],
      },
      {
        id: "kid-bayonet",
        title: "Bayonet Attack",
        family: "Classical",
        difficulty: "Sharp",
        goal: "Meet b4 with kingside speed: ...Nh5 and ...f5 before White's queenside play lands.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Control e4."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the bishop."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Complete the fianchetto."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Build the King's Indian shell."),
          white("Nf3", "g1f3"),
          black("O-O", "e8g8", "Castle first."),
          white("Be2", "f1e2"),
          black("e5", "e7e5", "Strike the center."),
          white("O-O", "e1g1"),
          black("Nc6", "b8c6", "Increase pressure before the center closes."),
          white("d5", "d4d5"),
          black("Ne7", "c6e7", "Reroute and prepare ...f5."),
          white("b4", "b2b4"),
          black("Nh5", "f6h5", "Ignore the wing race and build kingside threats."),
          white("Re1", "f1e1"),
          black("f5", "f7f5", "Start the attack before White opens queenside files."),
        ],
      },
      {
        id: "kid-exchange",
        title: "Exchange Variation",
        family: "Exchange",
        difficulty: "Core",
        goal: "Learn how to recapture and activate rooks after White trades in the center.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Develop and control e4."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the bishop."),
          white("Nc3", "b1c3"),
          black("Bg7", "f8g7", "Pressure the long diagonal."),
          white("e4", "e2e4"),
          black("d6", "d7d6", "Prepare ...e5."),
          white("Nf3", "g1f3"),
          black("O-O", "e8g8", "Castle before central trades."),
          white("Be2", "f1e2"),
          black("e5", "e7e5", "Challenge the center."),
          white("dxe5", "d4e5"),
          black("dxe5", "d6e5", "Recapture and keep central equality."),
          white("Qxd8", "d1d8"),
          black("Rxd8", "f8d8", "Use the rook actively after queens leave."),
          white("Bg5", "c1g5"),
          black("Re8", "d8e8", "Coordinate rooks and defend e5."),
          white("Nd5", "c3d5"),
          black("Nxd5", "f6d5", "Trade the advanced knight before it becomes permanent."),
        ],
      },
      {
        id: "kid-panno",
        title: "Panno vs Fianchetto",
        family: "Panno",
        difficulty: "Strategic",
        goal: "Use ...Nc6, ...a6, ...Rb8, and ...b5 to create queenside counterplay.",
        moves: [
          white("d4", "d2d4"),
          black("Nf6", "g8f6", "Control e4 and develop."),
          white("c4", "c2c4"),
          black("g6", "g7g6", "Prepare the fianchetto."),
          white("g3", "g2g3"),
          black("Bg7", "f8g7", "Match the long diagonal battle."),
          white("Bg2", "f1g2"),
          black("O-O", "e8g8", "Castle into safety."),
          white("Nc3", "b1c3"),
          black("d6", "d7d6", "Hold the center."),
          white("Nf3", "g1f3"),
          black("Nc6", "b8c6", "Develop actively instead of the quieter ...Nbd7."),
          white("O-O", "e1g1"),
          black("a6", "a7a6", "Prepare ...Rb8 and ...b5."),
          white("e4", "e2e4"),
          black("Rb8", "a8b8", "Put the rook behind the b-pawn push."),
          white("h3", "h2h3"),
          black("b5", "b7b5", "Challenge White's queenside space."),
          white("cxb5", "c4b5"),
          black("axb5", "a6b5", "Open the a-file/b-file structure for counterplay."),
        ],
      },
    ],
  },
];
